config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'projxes#index'
  
  resources :projxes do
    member do
      get :requests
      get :contributor_request
      get :accept_contributor_request
      delete :remove_contributor
    end
  end
  resources :users
  
  # get 'projxes/contributor_request'
end

app/models/contribution.rb
class Contribution < ActiveRecord::Base
  belongs_to :user
  belongs_to :projx
end

app/models/projx.rb
class Projx < ActiveRecord::Base
	belongs_to :user
  
  has_many :contribution_requests, -> { where(accepted: false) }, class_name: 'Contribution'
  has_many :contributions, -> { where(accepted: true) }
  has_many :contributors, through: :contributions, source: :user

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :projxes
  has_many :contribution_requests, -> { where(accepted: false) }, class_name: 'Contribution'
  has_many :contributions, -> { where(accepted: true) }
  has_many :contributed_projxes, through: :contributions, source: :projx
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password) }
	end

end

app/controllers/projxes_controller.rb
class ProjxesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_projx, only: [:show, :edit, :update, :destroy, :contributor_request, :requests, :accept_contributor_request, :remove_contributor]

  # GET /projxes
  # GET /projxes.json
  def index
    @projxes = Projx.all
    @users = User.all
  end

  # GET /projxes/1
  # GET /projxes/1.json
  def show
  end

  # GET /projxes/new
  def new
    @projx = current_user.projxes.build
  end

  # GET /projxes/1/edit
  def edit
  end

  # POST /projxes
  # POST /projxes.json
  def create
    @projx = current_user.projxes.build(projx_params)

    respond_to do |format|
      if @projx.save
        format.html { redirect_to @projx, notice: 'Projx was successfully created.' }
        format.json { render :show, status: :created, location: @projx }
      else
        format.html { render :new }
        format.json { render json: @projx.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projxes/1
  # PATCH/PUT /projxes/1.json
  def update
    respond_to do |format|
      if @projx.update(projx_params)
        format.html { redirect_to @projx, notice: 'Projx was successfully updated.' }
        format.json { render :show, status: :ok, location: @projx }
      else
        format.html { render :edit }
        format.json { render json: @projx.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projxes/1
  # DELETE /projxes/1.json
  def destroy
    @projx.destroy
    respond_to do |format|
      format.html { redirect_to projxes_url, notice: 'Projx was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def contributor_request
    if @projx.contribution_requests.where(:user_id => current_user.id).count < 1
      contribution_request = @projx.contribution_requests.build
      contribution_request.user = current_user
      if contribution_request.save
        redirect_to :back, notice: 'Contribution request made successfully.'
      else
        redirect_to :back, notice: 'There was an error in making your contribution request.'
      end
    else
      redirect_to :back, notice: 'You have already sent a request for this project.'
    end
  end

  def accept_contributor_request
    contribution_request = @projx.contribution_requests.find(params[:request_id])
    unless contribution_request.nil?
      contribution_request.accepted = true
      if contribution_request.save
        if @projx.contribution_requests.count > 0
          redirect_to requests_projx_path(@projx), notice: "Contribution request accepted successfully."
        else
          redirect_to @projx, notice: "Contribution request accepted successfully."
        end
      else
        redirect_to requests_projx_path(@projx), notice: "There was an error in accepting contribution request."
      end
    else
      redirect_to requests_projx_path(@projx), notice: "Could not find this contribution request."
    end
  end

  def remove_contributor
    contribution = @projx.contributions.find(params[:request_id])
    unless contribution.nil?
      if contribution.destroy
        if @projx.contributions.count > 0
          redirect_to requests_projx_path(@projx), notice: "Contributor removed successfully."
        else
          redirect_to @projx, notice: "Contributor removed successfully."
        end
      else
        redirect_to requests_projx_path(@projx), notice: "There was an error in removing contributor."
      end
    else
      redirect_to requests_projx_path(@projx), notice: "Could not find this user's contribution record."
    end
  end

  def requests
    @contribution_requests = @projx.contribution_requests
    @contributions = @projx.contributions
  end

  private

    def authenticate
      :authenticate_user! && current_user.try(:admin?)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_projx
      @projx = Projx.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def projx_params
      params.require(:projx).permit(:title, :content, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
	     @user = User.find(params[:id])
	end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projxes_helper.rb
module ProjxesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fiverr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<header id="main_navigation clearfix" style="padding:1.4em 5%;">
		<%= link_to "Association", root_path, style: 'text-decoration:none;text-transform:uppercase;font-size:1.5em;'%>
		<nav style="float:right;">
			<% if user_signed_in? %>
			<%= link_to "Home", root_path, style: "text-decoration:none;text-transform:uppercase;" %>
			<%= link_to "Logout", destroy_user_session_path, method: :delete, style: "text-decoration:none;text-transform:uppercase;margin-left:1em;" %>
			<% else %>
			<%= link_to "Signin", new_user_session_path, style: "text-decoration:none;text-transform:uppercase;" %>
			<%= link_to "Signup", new_user_registration_path, style: "text-decoration:none;text-transform:uppercase;margin-left:1em;" %>
			<% end  %>
		</nav>
	</header>

	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>


<%= yield %>

</body>
</html>

app/views/projxes/_form.html.erb
<%= form_for(@projx) do |f| %>
  <% if @projx.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@projx.errors.count, "error") %> prohibited this projx from being saved:</h2>

      <ul>
      <% @projx.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projxes/edit.html.erb
<h1>Editing Projx</h1>

<%= render 'form' %>

<%= link_to 'Show', @projx %> |
<%= link_to 'Back', projxes_path %>

app/views/projxes/index.html.erb
<p id="notice"><%= notice %></p>
<div style="text-align:center;">
  <h1>Listing Projxes</h1>

<% if current_user.try(:admin?) %>
  <div style="margin:4em 0;">
    <%= link_to 'New Projx', new_projx_path, style: 'background:#233250;padding:1em;border-radius:3px;color:white;text-decoration:none;' %>
  </div>
  <% end %>

      <% @projxes.each do |projx| %>
<div style="margin:0 auto;">
  <div style="background:#3C465C;height:130px;width:20%;margin:0 auto;padding:2.5em 1em 1em 1em;margin-bottom:1em;">
          <%= link_to projx.user.email, user_path(projx.user), style: 'text-decoration:none;color:white;' %><br />
          <br />
          <%= link_to projx.title, projx_path(projx), style: 'text-decoration:none;color:white;' %><br />
          <%= link_to projx.content, projx_path(projx), style: 'text-decoration:none;color:white;'  %>
          <br />
          <br />
          <% if current_user == projx.user %>
          <%= link_to 'Edit', edit_projx_path(projx), style: 'text-decoration:none;color:#ccc;' %>
          <%= link_to 'Destroy', projx, method: :delete, data: { confirm: 'Are you sure?' }, style: 'text-decoration:none;color:#ccc;' %>
          <%= link_to 'Show', projx, style: 'text-decoration:none;color:#ccc;' %>
          <% else %>
          <%= link_to 'Show', projx, style: 'text-decoration:none;color:#ccc;' %>
          <% end %>
  </div>
</div>
      <% end %>


  <br>
</div>

app/views/projxes/new.html.erb
<h1>New Projx</h1>

<%= render 'form' %>

<%= link_to 'Back', projxes_path %>

app/views/projxes/requests.html.erb
<% if current_user == @projx.user %>
  <div >
    <p> Accepted/Verified Post Contributors</p>
    <% @contribution_requests.each do |request| %>
      <img src="https://d13yacurqjgara.cloudfront.net/users/177698/screenshots/828493/billgates_1x.png" style="height:40px;width:40px;border-radius:100px;">
        <%= link_to "accept", accept_contributor_request_projx_path(@projx, request_id: request.id) %>
      <br />
    <% end %>
    <% @contributions.each do |request| %>
      <img src="https://d13yacurqjgara.cloudfront.net/users/177698/screenshots/828493/billgates_1x.png" style="height:40px;width:40px;border-radius:100px;">
        <%= link_to "remove", remove_contributor_projx_path(@projx, request_id: request.id), method: :delete %>
      <br />
    <% end %>
  </div>
<% end %>

app/views/projxes/show.html.erb
<div style="float:right;clear:left;">
  <p> Accepted/Verified Post Contributors</p>
  <% @projx.contributors.each do |contributor| %>
    <img src="https://d13yacurqjgara.cloudfront.net/users/177698/screenshots/828493/billgates_1x.png" style="height:40px;width:40px;border-radius:100px;">
  <% end %>
</div>

<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @projx.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @projx.content %>
</p>


<% if current_user == @projx.user %>
<%= link_to 'Edit', edit_projx_path(@projx) %> |
<%= link_to 'Back', projxes_path %>
<% else %>
<% end %>

<br />
<hr />

<% if current_user != @projx.user %>
  <% if @projx.contributors.any?{|cr| cr == current_user} %> 
    <%= link_to "Verified", '#', style: 'background:purple;padding:1em;color:white;border-radius:3px;text-decoration:none;' %>
  <% elsif !@projx.contribution_requests.any?{|cr| cr.user_id == current_user.id} %> 
    <%=  link_to "Request", contributor_request_projx_path(@projx), style: 'background:#272B28;padding:1em;color:white;border-radius:3px;text-decoration:none;' %>
  <% else %> 
    <%=  link_to "Pending", '#', style: 'background:blue;padding:1em;color:white;border-radius:3px;text-decoration:none;' %>
  <% end %>
<% end %>
<br />
<br />
<br />
<br />

<hr />

<% if current_user == @projx.user %>
  <% if @projx.contribution_requests.count > 0 %>
    <%=  link_to "New requests", requests_projx_path(@projx), style: 'background:#272B28;padding:1em;color:white;border-radius:3px;text-decoration:none;' %>
  <% elsif @projx.contributions.count > 0 %>
    <%=  link_to "Requests", requests_projx_path(@projx), style: 'background:#272B28;padding:1em;color:white;border-radius:3px;text-decoration:none;' %>
  <% else %>  
    No contribution requests.
  <% end %>
<% end %>
<br />
<br />
<br />

app/views/projxes/show_old.html.erb
<div style="float:right;clear:left;">
	<p> Accepted/Verified Post Contributors</p>

	<img src="https://d13yacurqjgara.cloudfront.net/users/177698/screenshots/828493/billgates_1x.png" style="height:40px;width:40px;border-radius:100px;">
	<img src="https://d13yacurqjgara.cloudfront.net/users/177698/screenshots/828493/billgates_1x.png" style="height:40px;width:40px;border-radius:100px;">
	<img src="https://d13yacurqjgara.cloudfront.net/users/177698/screenshots/828493/billgates_1x.png" style="height:40px;width:40px;border-radius:100px;">
	<img src="https://d13yacurqjgara.cloudfront.net/users/177698/screenshots/828493/billgates_1x.png" style="height:40px;width:40px;border-radius:100px;">
</div>

<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @projx.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @projx.content %>
</p>


<% if current_user == @projx.user %>
<%= link_to 'Edit', edit_projx_path(@projx) %> |
<%= link_to 'Back', projxes_path %>
<% else %>
<% end %>

<br />
<hr />

<p>if current_user =! projxes.user</p>

Before:
<%=  link_to "Request", '#', style: 'background:#272B28;padding:1em;color:white;border-radius:3px;text-decoration:none;' %>
After:
<%=  link_to "Pending", '#', style: 'background:blue;padding:1em;color:white;border-radius:3px;text-decoration:none;' %>
Accepted contributor:
<%= link_to "Verified", '#', style: 'background:purple;padding:1em;color:white;border-radius:3px;text-decoration:none;' %>
<br />
<br />
<br />
<br />

<hr />

<p>if current_user == projxes.user</p>

if contributions_request +1:
<%=  link_to "New requests", '#', style: 'background:#272B28;padding:1em;color:white;border-radius:3px;text-decoration:none;' %>
No contributor_request:
<br />
<br />
<br />
<p>When user clicks on button - render new view page with the following</p>

<div >
	<p> Accepted/Verified Post Contributors</p>

	<img src="https://d13yacurqjgara.cloudfront.net/users/177698/screenshots/828493/billgates_1x.png" style="height:40px;width:40px;border-radius:100px;">
	before: accept | after: remove
	<br />
	<img src="https://d13yacurqjgara.cloudfront.net/users/177698/screenshots/828493/billgates_1x.png" style="height:40px;width:40px;border-radius:100px;">
	before: accept | after: remove
	<br />
	<img src="https://d13yacurqjgara.cloudfront.net/users/177698/screenshots/828493/billgates_1x.png" style="height:40px;width:40px;border-radius:100px;">
	before: accept | after: remove
	<br />
	<img src="https://d13yacurqjgara.cloudfront.net/users/177698/screenshots/828493/billgates_1x.png" style="height:40px;width:40px;border-radius:100px;">
</div>

app/views/users/show.html.erb
<div style="text-align:center;">
	<h1>Profile</h1>
	<%= link_to @user.email, '#', style: 'text-align:center;' %>
</div>